### ISSUE TITLE
Whisper has no attribute "DecodingOptions"

### ISSUE THREAD

**Issue by tylerdurden4285** [dtbuchholz/yt-timestamps-subtitles#1]
When I try to run this using: 

> python main.py --file ~/filename.mp4

The result is: 

> Traceback (most recent call last):
>   File "/home/td/Code/yt-timestamps-subtitles/main.py", line 22, in <module>
>     options = whisper.DecodingOptions(fp16=False, language="en")
> AttributeError: module 'whisper' has no attribute 'DecodingOptions'

I tried also updating the pip and whisper and same results.

**Comment by dtbuchholz** [comment]
@tylerdurden4285 nice catch! the deps incorrectly specified the whisper package. 

I've updated and pushed to `main`. i also made a slight change to use `uv` for managing deps and running the script—see the updated README for pointers on how to get set up. and lmk if you still run into any issues.
